version: 2
registries:
  common-libraries:
    type: npm-registry
    url: https://cookunity-mobile-853384537270.d.codeartifact.us-east-1.amazonaws.com/npm/common-libraries/
    token: ${{ secrets.CODEARTIFACT_AUTH_TOKEN }}
  ui:
    type: npm-registry
    url: https://cookunity-mobile-853384537270.d.codeartifact.us-east-1.amazonaws.com/npm/ui/
    token: ${{ secrets.CODEARTIFACT_AUTH_TOKEN }}
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  cooldown:
    semver-minor-days: 7
    semver-major-days: 15
  registries:
  - common-libraries
  - ui
  commit-message:
    prefix: chore
    include: scope
  labels:
  - dependencies
  - npm
